// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: serialization/packets.proto

package no.elg.infiniteBootleg.protobuf;

public final class Packets {
  private Packets() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BlockUpdatePacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:packets.BlockUpdatePacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.persistence.Vector2i pos = 1;</code>
     * @return Whether the pos field is set.
     */
    boolean hasPos();
    /**
     * <code>.persistence.Vector2i pos = 1;</code>
     * @return The pos.
     */
    no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2i getPos();
    /**
     * <code>.persistence.Vector2i pos = 1;</code>
     */
    no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2iOrBuilder getPosOrBuilder();
  }
  /**
   * Protobuf type {@code packets.BlockUpdatePacket}
   */
  public static final class BlockUpdatePacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:packets.BlockUpdatePacket)
      BlockUpdatePacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BlockUpdatePacket.newBuilder() to construct.
    private BlockUpdatePacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BlockUpdatePacket() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BlockUpdatePacket();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BlockUpdatePacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2i.Builder subBuilder = null;
              if (pos_ != null) {
                subBuilder = pos_.toBuilder();
              }
              pos_ = input.readMessage(no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2i.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(pos_);
                pos_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return no.elg.infiniteBootleg.protobuf.Packets.internal_static_packets_BlockUpdatePacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return no.elg.infiniteBootleg.protobuf.Packets.internal_static_packets_BlockUpdatePacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket.class, no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket.Builder.class);
    }

    public static final int POS_FIELD_NUMBER = 1;
    private no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2i pos_;
    /**
     * <code>.persistence.Vector2i pos = 1;</code>
     * @return Whether the pos field is set.
     */
    @java.lang.Override
    public boolean hasPos() {
      return pos_ != null;
    }
    /**
     * <code>.persistence.Vector2i pos = 1;</code>
     * @return The pos.
     */
    @java.lang.Override
    public no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2i getPos() {
      return pos_ == null ? no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2i.getDefaultInstance() : pos_;
    }
    /**
     * <code>.persistence.Vector2i pos = 1;</code>
     */
    @java.lang.Override
    public no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2iOrBuilder getPosOrBuilder() {
      return getPos();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pos_ != null) {
        output.writeMessage(1, getPos());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (pos_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPos());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket)) {
        return super.equals(obj);
      }
      no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket other = (no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket) obj;

      if (hasPos() != other.hasPos()) return false;
      if (hasPos()) {
        if (!getPos()
            .equals(other.getPos())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPos()) {
        hash = (37 * hash) + POS_FIELD_NUMBER;
        hash = (53 * hash) + getPos().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code packets.BlockUpdatePacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:packets.BlockUpdatePacket)
        no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return no.elg.infiniteBootleg.protobuf.Packets.internal_static_packets_BlockUpdatePacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return no.elg.infiniteBootleg.protobuf.Packets.internal_static_packets_BlockUpdatePacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket.class, no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket.Builder.class);
      }

      // Construct using no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (posBuilder_ == null) {
          pos_ = null;
        } else {
          pos_ = null;
          posBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return no.elg.infiniteBootleg.protobuf.Packets.internal_static_packets_BlockUpdatePacket_descriptor;
      }

      @java.lang.Override
      public no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket getDefaultInstanceForType() {
        return no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket.getDefaultInstance();
      }

      @java.lang.Override
      public no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket build() {
        no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket buildPartial() {
        no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket result = new no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket(this);
        if (posBuilder_ == null) {
          result.pos_ = pos_;
        } else {
          result.pos_ = posBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket) {
          return mergeFrom((no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket other) {
        if (other == no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket.getDefaultInstance()) return this;
        if (other.hasPos()) {
          mergePos(other.getPos());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2i pos_;
      private com.google.protobuf.SingleFieldBuilderV3<
          no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2i, no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2i.Builder, no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2iOrBuilder> posBuilder_;
      /**
       * <code>.persistence.Vector2i pos = 1;</code>
       * @return Whether the pos field is set.
       */
      public boolean hasPos() {
        return posBuilder_ != null || pos_ != null;
      }
      /**
       * <code>.persistence.Vector2i pos = 1;</code>
       * @return The pos.
       */
      public no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2i getPos() {
        if (posBuilder_ == null) {
          return pos_ == null ? no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2i.getDefaultInstance() : pos_;
        } else {
          return posBuilder_.getMessage();
        }
      }
      /**
       * <code>.persistence.Vector2i pos = 1;</code>
       */
      public Builder setPos(no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2i value) {
        if (posBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pos_ = value;
          onChanged();
        } else {
          posBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.persistence.Vector2i pos = 1;</code>
       */
      public Builder setPos(
          no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2i.Builder builderForValue) {
        if (posBuilder_ == null) {
          pos_ = builderForValue.build();
          onChanged();
        } else {
          posBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.persistence.Vector2i pos = 1;</code>
       */
      public Builder mergePos(no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2i value) {
        if (posBuilder_ == null) {
          if (pos_ != null) {
            pos_ =
              no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2i.newBuilder(pos_).mergeFrom(value).buildPartial();
          } else {
            pos_ = value;
          }
          onChanged();
        } else {
          posBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.persistence.Vector2i pos = 1;</code>
       */
      public Builder clearPos() {
        if (posBuilder_ == null) {
          pos_ = null;
          onChanged();
        } else {
          pos_ = null;
          posBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.persistence.Vector2i pos = 1;</code>
       */
      public no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2i.Builder getPosBuilder() {
        
        onChanged();
        return getPosFieldBuilder().getBuilder();
      }
      /**
       * <code>.persistence.Vector2i pos = 1;</code>
       */
      public no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2iOrBuilder getPosOrBuilder() {
        if (posBuilder_ != null) {
          return posBuilder_.getMessageOrBuilder();
        } else {
          return pos_ == null ?
              no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2i.getDefaultInstance() : pos_;
        }
      }
      /**
       * <code>.persistence.Vector2i pos = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2i, no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2i.Builder, no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2iOrBuilder> 
          getPosFieldBuilder() {
        if (posBuilder_ == null) {
          posBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2i, no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2i.Builder, no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2iOrBuilder>(
                  getPos(),
                  getParentForChildren(),
                  isClean());
          pos_ = null;
        }
        return posBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:packets.BlockUpdatePacket)
    }

    // @@protoc_insertion_point(class_scope:packets.BlockUpdatePacket)
    private static final no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket();
    }

    public static no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BlockUpdatePacket>
        PARSER = new com.google.protobuf.AbstractParser<BlockUpdatePacket>() {
      @java.lang.Override
      public BlockUpdatePacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BlockUpdatePacket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BlockUpdatePacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BlockUpdatePacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public no.elg.infiniteBootleg.protobuf.Packets.BlockUpdatePacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_packets_BlockUpdatePacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_packets_BlockUpdatePacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033serialization/packets.proto\022\007packets\032\037" +
      "serialization/persistence.proto\"7\n\021Block" +
      "UpdatePacket\022\"\n\003pos\030\001 \001(\0132\025.persistence." +
      "Vector2iB,\n\037no.elg.infiniteBootleg.proto" +
      "bufB\007PacketsP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          no.elg.infiniteBootleg.protobuf.ProtoWorld.getDescriptor(),
        });
    internal_static_packets_BlockUpdatePacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_packets_BlockUpdatePacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_packets_BlockUpdatePacket_descriptor,
        new java.lang.String[] { "Pos", });
    no.elg.infiniteBootleg.protobuf.ProtoWorld.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
