// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: serialization/packets.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package no.elg.infiniteBootleg.protobuf;

@kotlin.jvm.JvmName("-initializeentityRequest")
public inline fun entityRequest(block: no.elg.infiniteBootleg.protobuf.EntityRequestKt.Dsl.() -> kotlin.Unit): no.elg.infiniteBootleg.protobuf.Packets.EntityRequest =
  no.elg.infiniteBootleg.protobuf.EntityRequestKt.Dsl._create(no.elg.infiniteBootleg.protobuf.Packets.EntityRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `packets.EntityRequest`
 */
public object EntityRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: no.elg.infiniteBootleg.protobuf.Packets.EntityRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: no.elg.infiniteBootleg.protobuf.Packets.EntityRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): no.elg.infiniteBootleg.protobuf.Packets.EntityRequest = _builder.build()

    /**
     * `string uuid = 1;`
     */
    public var uuid: kotlin.String
      @JvmName("getUuid")
      get() = _builder.getUuid()
      @JvmName("setUuid")
      set(value) {
        _builder.setUuid(value)
      }
    /**
     * `string uuid = 1;`
     */
    public fun clearUuid() {
      _builder.clearUuid()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun no.elg.infiniteBootleg.protobuf.Packets.EntityRequest.copy(block: no.elg.infiniteBootleg.protobuf.EntityRequestKt.Dsl.() -> kotlin.Unit): no.elg.infiniteBootleg.protobuf.Packets.EntityRequest =
  no.elg.infiniteBootleg.protobuf.EntityRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

