// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: serialization/packets.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package no.elg.infiniteBootleg.protobuf;

@kotlin.jvm.JvmName("-initializelogin")
public inline fun login(block: no.elg.infiniteBootleg.protobuf.LoginKt.Dsl.() -> kotlin.Unit): no.elg.infiniteBootleg.protobuf.Packets.Login =
  no.elg.infiniteBootleg.protobuf.LoginKt.Dsl._create(no.elg.infiniteBootleg.protobuf.Packets.Login.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `packets.Login`
 */
public object LoginKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: no.elg.infiniteBootleg.protobuf.Packets.Login.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: no.elg.infiniteBootleg.protobuf.Packets.Login.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): no.elg.infiniteBootleg.protobuf.Packets.Login = _builder.build()

    /**
     * `string uuid = 1;`
     */
    public var uuid: kotlin.String
      @JvmName("getUuid")
      get() = _builder.getUuid()
      @JvmName("setUuid")
      set(value) {
        _builder.setUuid(value)
      }
    /**
     * `string uuid = 1;`
     */
    public fun clearUuid() {
      _builder.clearUuid()
    }

    /**
     * `string username = 2;`
     */
    public var username: kotlin.String
      @JvmName("getUsername")
      get() = _builder.getUsername()
      @JvmName("setUsername")
      set(value) {
        _builder.setUsername(value)
      }
    /**
     * `string username = 2;`
     */
    public fun clearUsername() {
      _builder.clearUsername()
    }

    /**
     * ```
     *client version
     * ```
     *
     * `string version = 3;`
     */
    public var version: kotlin.String
      @JvmName("getVersion")
      get() = _builder.getVersion()
      @JvmName("setVersion")
      set(value) {
        _builder.setVersion(value)
      }
    /**
     * ```
     *client version
     * ```
     *
     * `string version = 3;`
     */
    public fun clearVersion() {
      _builder.clearVersion()
    }
  }
}
@kotlin.jvm.JvmSynthetic
@com.google.errorprone.annotations.CheckReturnValue
public inline fun no.elg.infiniteBootleg.protobuf.Packets.Login.copy(block: no.elg.infiniteBootleg.protobuf.LoginKt.Dsl.() -> kotlin.Unit): no.elg.infiniteBootleg.protobuf.Packets.Login =
  no.elg.infiniteBootleg.protobuf.LoginKt.Dsl._create(this.toBuilder()).apply { block() }._build()

