// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: serialization/packets.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package no.elg.infiniteBootleg.protobuf;

@kotlin.jvm.JvmName("-initializesecretExchange")
public inline fun secretExchange(block: no.elg.infiniteBootleg.protobuf.SecretExchangeKt.Dsl.() -> kotlin.Unit): no.elg.infiniteBootleg.protobuf.Packets.SecretExchange =
  no.elg.infiniteBootleg.protobuf.SecretExchangeKt.Dsl._create(no.elg.infiniteBootleg.protobuf.Packets.SecretExchange.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `packets.SecretExchange`
 */
public object SecretExchangeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: no.elg.infiniteBootleg.protobuf.Packets.SecretExchange.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: no.elg.infiniteBootleg.protobuf.Packets.SecretExchange.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): no.elg.infiniteBootleg.protobuf.Packets.SecretExchange = _builder.build()

    /**
     * `string entityUUID = 1;`
     */
    public var entityUUID: kotlin.String
      @JvmName("getEntityUUID")
      get() = _builder.getEntityUUID()
      @JvmName("setEntityUUID")
      set(value) {
        _builder.setEntityUUID(value)
      }
    /**
     * `string entityUUID = 1;`
     */
    public fun clearEntityUUID() {
      _builder.clearEntityUUID()
    }

    /**
     * `string secret = 2;`
     */
    public var secret: kotlin.String
      @JvmName("getSecret")
      get() = _builder.getSecret()
      @JvmName("setSecret")
      set(value) {
        _builder.setSecret(value)
      }
    /**
     * `string secret = 2;`
     */
    public fun clearSecret() {
      _builder.clearSecret()
    }
  }
}
@kotlin.jvm.JvmSynthetic
@com.google.errorprone.annotations.CheckReturnValue
public inline fun no.elg.infiniteBootleg.protobuf.Packets.SecretExchange.copy(block: no.elg.infiniteBootleg.protobuf.SecretExchangeKt.Dsl.() -> kotlin.Unit): no.elg.infiniteBootleg.protobuf.Packets.SecretExchange =
  no.elg.infiniteBootleg.protobuf.SecretExchangeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

