// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: serialization/packets.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package no.elg.infiniteBootleg.protobuf;

@kotlin.jvm.JvmName("-initializeserverLoginStatus")
public inline fun serverLoginStatus(block: no.elg.infiniteBootleg.protobuf.ServerLoginStatusKt.Dsl.() -> kotlin.Unit): no.elg.infiniteBootleg.protobuf.Packets.ServerLoginStatus =
  no.elg.infiniteBootleg.protobuf.ServerLoginStatusKt.Dsl._create(no.elg.infiniteBootleg.protobuf.Packets.ServerLoginStatus.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `packets.ServerLoginStatus`
 */
public object ServerLoginStatusKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: no.elg.infiniteBootleg.protobuf.Packets.ServerLoginStatus.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: no.elg.infiniteBootleg.protobuf.Packets.ServerLoginStatus.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): no.elg.infiniteBootleg.protobuf.Packets.ServerLoginStatus = _builder.build()

    /**
     * `.packets.ServerLoginStatus.ServerStatus status = 1;`
     */
    public var status: no.elg.infiniteBootleg.protobuf.Packets.ServerLoginStatus.ServerStatus
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    public var statusValue: kotlin.Int
      @JvmName("getStatusValue")
      get() = _builder.getStatusValue()
      @JvmName("setStatusValue")
      set(value) {
        _builder.setStatusValue(value)
      }
    /**
     * `.packets.ServerLoginStatus.ServerStatus status = 1;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun no.elg.infiniteBootleg.protobuf.Packets.ServerLoginStatus.copy(block: no.elg.infiniteBootleg.protobuf.ServerLoginStatusKt.Dsl.() -> kotlin.Unit): no.elg.infiniteBootleg.protobuf.Packets.ServerLoginStatus =
  no.elg.infiniteBootleg.protobuf.ServerLoginStatusKt.Dsl._create(this.toBuilder()).apply { block() }._build()

