// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: serialization/packets.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package no.elg.infiniteBootleg.protobuf;

@kotlin.jvm.JvmName("-initializespawnEntity")
public inline fun spawnEntity(block: no.elg.infiniteBootleg.protobuf.SpawnEntityKt.Dsl.() -> kotlin.Unit): no.elg.infiniteBootleg.protobuf.Packets.SpawnEntity =
  no.elg.infiniteBootleg.protobuf.SpawnEntityKt.Dsl._create(no.elg.infiniteBootleg.protobuf.Packets.SpawnEntity.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `packets.SpawnEntity`
 */
public object SpawnEntityKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: no.elg.infiniteBootleg.protobuf.Packets.SpawnEntity.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: no.elg.infiniteBootleg.protobuf.Packets.SpawnEntity.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): no.elg.infiniteBootleg.protobuf.Packets.SpawnEntity = _builder.build()

    /**
     * `.persistence.Entity entity = 1;`
     */
    public var entity: no.elg.infiniteBootleg.protobuf.ProtoWorld.Entity
      @JvmName("getEntity")
      get() = _builder.getEntity()
      @JvmName("setEntity")
      set(value) {
        _builder.setEntity(value)
      }
    /**
     * `.persistence.Entity entity = 1;`
     */
    public fun clearEntity() {
      _builder.clearEntity()
    }
    /**
     * `.persistence.Entity entity = 1;`
     * @return Whether the entity field is set.
     */
    public fun hasEntity(): kotlin.Boolean {
      return _builder.hasEntity()
    }

    /**
     * `string uuid = 2;`
     */
    public var uuid: kotlin.String
      @JvmName("getUuid")
      get() = _builder.getUuid()
      @JvmName("setUuid")
      set(value) {
        _builder.setUuid(value)
      }
    /**
     * `string uuid = 2;`
     */
    public fun clearUuid() {
      _builder.clearUuid()
    }
  }
}
@kotlin.jvm.JvmSynthetic
@com.google.errorprone.annotations.CheckReturnValue
public inline fun no.elg.infiniteBootleg.protobuf.Packets.SpawnEntity.copy(block: no.elg.infiniteBootleg.protobuf.SpawnEntityKt.Dsl.() -> kotlin.Unit): no.elg.infiniteBootleg.protobuf.Packets.SpawnEntity =
  no.elg.infiniteBootleg.protobuf.SpawnEntityKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val no.elg.infiniteBootleg.protobuf.Packets.SpawnEntityOrBuilder.entityOrNull: no.elg.infiniteBootleg.protobuf.ProtoWorld.Entity?
  get() = if (hasEntity()) getEntity() else null

