// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: serialization/persistence.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package no.elg.infiniteBootleg.protobuf;

@kotlin.jvm.JvmName("-initializevector2f")
public inline fun vector2f(block: no.elg.infiniteBootleg.protobuf.Vector2fKt.Dsl.() -> kotlin.Unit): no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2f =
  no.elg.infiniteBootleg.protobuf.Vector2fKt.Dsl._create(no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2f.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `persistence.Vector2f`
 */
public object Vector2fKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2f.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2f.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2f = _builder.build()

    /**
     * `float x = 1;`
     */
    public var x: kotlin.Float
      @JvmName("getX")
      get() = _builder.getX()
      @JvmName("setX")
      set(value) {
        _builder.setX(value)
      }
    /**
     * `float x = 1;`
     */
    public fun clearX() {
      _builder.clearX()
    }

    /**
     * `float y = 2;`
     */
    public var y: kotlin.Float
      @JvmName("getY")
      get() = _builder.getY()
      @JvmName("setY")
      set(value) {
        _builder.setY(value)
      }
    /**
     * `float y = 2;`
     */
    public fun clearY() {
      _builder.clearY()
    }
  }
}
@kotlin.jvm.JvmSynthetic
@com.google.errorprone.annotations.CheckReturnValue
public inline fun no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2f.copy(block: no.elg.infiniteBootleg.protobuf.Vector2fKt.Dsl.() -> kotlin.Unit): no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2f =
  no.elg.infiniteBootleg.protobuf.Vector2fKt.Dsl._create(this.toBuilder()).apply { block() }._build()

