// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: serialization/packets.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package no.elg.infiniteBootleg.protobuf;

@kotlin.jvm.JvmName("-initializeworldSettings")
public inline fun worldSettings(block: no.elg.infiniteBootleg.protobuf.WorldSettingsKt.Dsl.() -> kotlin.Unit): no.elg.infiniteBootleg.protobuf.Packets.WorldSettings =
  no.elg.infiniteBootleg.protobuf.WorldSettingsKt.Dsl._create(no.elg.infiniteBootleg.protobuf.Packets.WorldSettings.newBuilder()).apply { block() }._build()
/**
 * ```
 *if not present, do not update setting
 * ```
 *
 * Protobuf type `packets.WorldSettings`
 */
public object WorldSettingsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: no.elg.infiniteBootleg.protobuf.Packets.WorldSettings.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: no.elg.infiniteBootleg.protobuf.Packets.WorldSettings.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): no.elg.infiniteBootleg.protobuf.Packets.WorldSettings = _builder.build()

    /**
     * `optional float time = 1;`
     */
    public var time: kotlin.Float
      @JvmName("getTime")
      get() = _builder.getTime()
      @JvmName("setTime")
      set(value) {
        _builder.setTime(value)
      }
    /**
     * `optional float time = 1;`
     */
    public fun clearTime() {
      _builder.clearTime()
    }
    /**
     * `optional float time = 1;`
     * @return Whether the time field is set.
     */
    public fun hasTime(): kotlin.Boolean {
      return _builder.hasTime()
    }

    /**
     * `optional float timeScale = 2;`
     */
    public var timeScale: kotlin.Float
      @JvmName("getTimeScale")
      get() = _builder.getTimeScale()
      @JvmName("setTimeScale")
      set(value) {
        _builder.setTimeScale(value)
      }
    /**
     * `optional float timeScale = 2;`
     */
    public fun clearTimeScale() {
      _builder.clearTimeScale()
    }
    /**
     * `optional float timeScale = 2;`
     * @return Whether the timeScale field is set.
     */
    public fun hasTimeScale(): kotlin.Boolean {
      return _builder.hasTimeScale()
    }

    /**
     * `optional .persistence.Vector2i spawn = 3;`
     */
    public var spawn: no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2i
      @JvmName("getSpawn")
      get() = _builder.getSpawn()
      @JvmName("setSpawn")
      set(value) {
        _builder.setSpawn(value)
      }
    /**
     * `optional .persistence.Vector2i spawn = 3;`
     */
    public fun clearSpawn() {
      _builder.clearSpawn()
    }
    /**
     * `optional .persistence.Vector2i spawn = 3;`
     * @return Whether the spawn field is set.
     */
    public fun hasSpawn(): kotlin.Boolean {
      return _builder.hasSpawn()
    }
    public val WorldSettingsKt.Dsl.spawnOrNull: no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2i?
      get() = _builder.spawnOrNull
  }
}
@kotlin.jvm.JvmSynthetic
@com.google.errorprone.annotations.CheckReturnValue
public inline fun no.elg.infiniteBootleg.protobuf.Packets.WorldSettings.copy(block: no.elg.infiniteBootleg.protobuf.WorldSettingsKt.Dsl.() -> kotlin.Unit): no.elg.infiniteBootleg.protobuf.Packets.WorldSettings =
  no.elg.infiniteBootleg.protobuf.WorldSettingsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val no.elg.infiniteBootleg.protobuf.Packets.WorldSettingsOrBuilder.spawnOrNull: no.elg.infiniteBootleg.protobuf.ProtoWorld.Vector2i?
  get() = if (hasSpawn()) getSpawn() else null

